version: '0.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/core:/etc/nginx/conf.d
      - ./nginx/www:/var/www/
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/html:/usr/share/nginx/html/
    links:
      - php

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bigsugardady
      - MYSQL_DATABASE=mylittleserver
      - MYSQL_USER=mylittleuser
      - MYSQL_PASSWORD=mylittlepassword
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build: ./php
    container_name: php-fpm
    links:
      - mysql
    volumes:
      - ./nginx/www:/var/www